### PR TITLE
Update for Step 4

### PR DESCRIPTION
**Pull request by e-yang08**
## What
- Incorporate change from the upstream
- Modify the dockerfile to run python (Step 4-4)
- Modify the dockerfile to run the listing API (Step 4-6)

## HOW
※ for both Step 4-4 & 4-6

Firstly, set the directory.
```
$ cd .mercari-build-training-2022
```

Run the following two commands
```
docker build -t build2022/app:latest -f python/dockerfile .
docker run -dp 9000:9000 build2022/app:latest
```

For step 4-4, it will return the current version of python installed in your local.
For step 4-6, it will launch the listing API.

You can open another terminal and run some of the curl commands to check if it works.
Examples are listed below.
```
# POST the item with its jpg file
$ curl -X POST \
  --url 'http://localhost:9000/items' \
  -F 'name=jacket' \
  -F 'category=fashion' \
  -F 'image=@images/default.jpg'

# GET item list
$ curl -X GET 'http://127.0.0.1:9000/items'
{
 "items": [
  {
   "name": "jacket",
   "category": "fashion",
"image":"<hash>.jpg"
  }
 ]
}

# GET item list
$ curl -X GET 'http://127.0.0.1:9000/items/1'
{
 "items": [
  {
   "name": "jacket",
   "category": "fashion",
"image":"<hash>.jpg"
  }
 ]
}


# request item with name "jacket"
$ curl -X GET 'http://127.0.0.1:9000/search?keyword=jacket'
{
 "items": [
  {
   "name": "jacket",
   "category": "fashion"
"image":"<hash>.jpg"
  }
 ]
}
```

## CHECKS :warning:
Please make sure you are aware of the following.
- [x] **The changes in this PR doesn't have private information

### CODE REVIEW

**Review by e-yang08 — COMMENTED** [review]
In line 4, I tried to just move db/items.db since I thought sqlite3 file already contained some items and I wanted to create a brandnew database in the docker. However, when I replace `COPY db ./db` with `COPY db/items.db ./db` and launch the app, I receive `curl: (52) Empty reply from server` upon running any curl commands. 

I guess the root reason could be sqlite3 file is not made upon `@app.on_event("startup")` for some reasons, but I'm not fully sure about it.

**Comment by manami-bunbun** [comment]
> 

I'm not sure, but when you build a docker image with `COPY db/items.db . /db`, doesn't that mean you're trying to copy a directory to a file? How about` COPY db/items.db  /db/items.db`  ?
Or maybe you are copying home/db to db, and when running, Sqlite3 can't find the file because the paths are different when connecting...?
Again, I'm not sure!

**Review by manami-bunbun — COMMENTED** [review]
LGTM other than the dockerfile....wait for another review!

**Comment by tkat0** [comment]
💡 

https://docs.docker.com/engine/reference/builder/#copy

>If multiple <src> resources are specified, either directly or due to the use of a wildcard, then <dest> must be a directory, and it must end with a slash /.

**Review by tkat0 — APPROVED** [review]

**Comment by e-yang08** [comment]
Thank you so much for all the reviews! I really appreciated it.

The question I had initially is that I was able to copy only item.db file, but for some reason, I kept receiving `curl: (52) Empty reply from server` error. I tried to check the repository structure within the docker container (e.g., running `docker exec -it [container id] /bin/bash`) but I couldn't figure out how exactly I can check. The docker log shows `FileNotFoundError: [Errno 2] No such file or directory: '/../db/mercari.sqlite3'`, so I have been tring to recheck main.py and dockerfile but have not been able to solve it.

**Pull request merged**
